### ISSUE TITLE
Design Badges

### ISSUE THREAD

**Issue by asmaaaah** [Dyslexia-Done/online-reading-tutor#12]
- [ ] assets

- [ ] page design

**Comment by asmaaaah** [comment]
- [ ] assets

- [ ] page design

**Comment by natashadecoste** [comment]
I added a sidescrolling carousel _for now_ on the profile for viewing the badges
I started to do one for completing the first lesson and one for the disabled/locked badges.
svgs will be uploaded to the repo (in PR)


##### first badge
![image](https://user-images.githubusercontent.com/14351335/79403985-65375580-7f5e-11ea-8f6e-5625f0384e50.png)


##### disabled/locked badge
![image](https://user-images.githubusercontent.com/14351335/79403974-5c468400-7f5e-11ea-9f54-cb95d1ffb37e.png)

**Comment by aniprasad** [comment]
Fyi, I integrated this into my branch `badge-screen` 
Will be the badges be the same for all achievements?

**Comment by natashadecoste** [comment]
updated the designs and made a PR to merge them: #46 

![locked](https://user-images.githubusercontent.com/14351335/80604881-4b871b00-8a00-11ea-9860-f9ba99c0da08.png)

![01](https://user-images.githubusercontent.com/14351335/80604836-3f9b5900-8a00-11ea-87b1-fe35c2abb6a6.png)
