### ISSUE TITLE
Badge 

### ISSUE THREAD

**Issue by asmaaaah** [Dyslexia-Done/online-reading-tutor#17]

**Comment by syedayus** [comment]
Award a badge to students once the lesson is complete

**Comment by syedayus** [comment]
Early achiever badge: Give a badge to a student when they start a new lesson
Every 5 or 10 lessons: Milestone badges 
Badges for completed worlds

**Comment by asmaaaah** [comment]
- Fire World Batch
- Month Streak Batch
