### ISSUE TITLE
Create File to store data

### ISSUE THREAD

**Issue by asmaaaah** [Dyslexia-Done/online-reading-tutor#34]
Mimic database
- [ ] Streaks
- [ ] badges
- [ ] completed lessons

**Comment by aniprasad** [comment]
Some possible information that might be useful:

For Badges (currently) we have,

1. Badge Names
2. Badge Image Names
3. Badge IDs
4. Badge States
5. Badge array encapsulating 1-4

For Worlds,  what might be useful,
1. World Name
2. World ID
3. World Completion State
3. "Lessons" in each World

For Lessons, what might be useful,
1. Lesson Name
2. Lesson ID
3. Lesson State - either incomplete / complete
(Some of the lesson information should be encapsulated in the "Worlds" object as well)
