### ISSUE TITLE
Design the world map

### ISSUE THREAD

**Issue by asmaaaah** [Dyslexia-Done/online-reading-tutor#5]
- [ ] ice world svgs
- [ ] fire world svgs
- [ ] screen(s)

**Comment by natashadecoste** [comment]
i added the palette into the code (PR : #23) and we can make the background uiBackground. 
I might change the card styles a bit too. 
![lessons-dark](https://user-images.githubusercontent.com/14351335/79404948-14752c00-7f61-11ea-851b-8f882157404d.png)
